version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - integration_network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret
      MYSQL_DATABASE: integration_api
    ports:
      - "3306:3306"
    volumes:             
      - ./sql_init:/docker-entrypoint-initdb.d
    networks:
      - integration_network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - integration_network
      
networks:
  integration_network:
    driver: bridge